import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useEffect, useMemo } from "react";
import { ControlPanel } from "./components/ControlPanel";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { SubtitleBar } from "./components/SubtitleBar";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useSfxPlayer } from "./hooks/useSfxPlayer";
import { useStepper } from "./hooks/useStepper";
import { useSubtitles } from "./hooks/useSubtitles";
import { CHAPTERS } from "./registry/chapters";
import { installVideoController } from "./lib/video-controller";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

function readRenderMode(): boolean {
  if (typeof window === "undefined") return false;
  return new URLSearchParams(window.location.search).get("render") === "1";
}

export default function App() {
  const isRenderMode = useMemo(() => readRenderMode(), []);

  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  const { mode, setMode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();
  const { subtitlesEnabled, setSubtitlesEnabled } = useSubtitles();

  // Mount video controller for headless renderer (wvp-render)
  useEffect(() => {
    if (isRenderMode) {
      installVideoController(CHAPTERS, stepper.jumpToGlobal);
    }
  }, [isRenderMode, stepper.jumpToGlobal]);

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;
  const sfxBaseSrc =
    mode === "manual"
      ? null
      : `${import.meta.env.BASE_URL}sfx/${ch.id}/${stepper.cursor.step + 1}`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  const onPlay = useCallback(() => {
    setMode("auto");
    setAutoStarted(true);
  }, [setMode, setAutoStarted]);

  const onPause = useCallback(() => {
    setMode("manual");
  }, [setMode]);

  // Expose globals for recording-script completion detection
  useEffect(() => {
    (window as any).__CURRENT_GLOBAL_INDEX__ = stepper.globalIndex;
    (window as any).__TOTAL_STEPS__ = stepper.totalGlobal;
  }, [stepper.globalIndex, stepper.totalGlobal]);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });
  useSfxPlayer({
    baseSrc: sfxBaseSrc,
    mode,
    autoStarted,
  });

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={ch.id} className="scene">
          <Cmp step={stepper.cursor.step} />
        </div>
        <SubtitleBar text={stepText} visible={subtitlesEnabled} />
      </Stage>
      {!isRenderMode && (
        <>
          <ProgressBar
            chapters={CHAPTERS}
            cursor={stepper.cursor}
            onJumpChapter={stepper.jumpToChapter}
          />
          <ControlPanel
            chapters={CHAPTERS}
            cursor={stepper.cursor}
            globalIndex={stepper.globalIndex}
            totalGlobal={stepper.totalGlobal}
            mode={mode}
            autoStarted={autoStarted}
            subtitlesEnabled={subtitlesEnabled}
            onSubtitlesChange={setSubtitlesEnabled}
            onPlay={onPlay}
            onPause={onPause}
            onPrev={stepper.prev}
            onNext={stepper.next}
            onJumpChapter={stepper.jumpToChapter}
          />
        </>
      )}
    </>
  );
}
